# Generated by Django 5.1 on 2024-08-17 14:38

import backend.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 8, 17, 15, 38, 18, 550107))),
                ('img', models.ImageField(blank=True, null=True, upload_to=backend.models.f)),
            ],
        ),
    ]
