# Generated by Django 5.1 on 2024-08-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='default name', max_length=20),
            preserve_default=False,
        ),
    ]
